[build]
publish = "public"
command = "&& hugo && chmod +x generateDocFormats.sh && ./generateDocFormats.sh public/word-lists"

[build.environment]
HUGO_VERSION = "0.111.3"

[context.deploy-preview]
command = " hugo && chmod +x generateDocFormats.sh && ./generateDocFormats.sh public/word-lists"

[context.branch-deploy]
command = "hugo && chmod +x generateDocFormats.sh && ./generateDocFormats.sh public/word-lists"
